# Generated by Django 3.2.5 on 2021-11-30 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='ceo',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='business_ceo', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Insira número no formato (xx) 98765-4321', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_business', to='user.business'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.business')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('paid_out', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=300, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'isclient': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.service')),
            ],
        ),
    ]
