# Generated by Django 3.2.5 on 2021-12-03 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_squashed_0008_alter_business_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invitations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'business': None}, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Insira apenas dígitos no formato (xx) 98765-4321.', max_length=11, null=True, unique=True),
        ),
    ]
