# Generated by Django 3.2.5 on 2021-12-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211130_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'service categories'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Insira número no formato (xx) 98765-4321', max_length=11, null=True, unique=True),
        ),
    ]
