# Generated by Django 3.2.5 on 2021-12-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211130_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'service categories'},
        ),
        migrations.AddField(
            model_name='business',
            name='invitations',
            field=models.ManyToManyField(blank=True, null=True, to='user.Business'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Insira número no formato (xx) 98765-4321', max_length=11, null=True, unique=True),
        ),
    ]
