# Generated by Django 3.2.5 on 2021-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211203_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.SmallIntegerField(),
        ),
    ]
