# Generated by Django 3.2.5 on 2021-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211202_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.DurationField()),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
