# Generated by Django 3.2.5 on 2021-12-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invitations',
            field=models.ManyToManyField(blank=True, to='user.Business'),
        ),
    ]
