# Generated by Django 3.2.5 on 2021-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_business_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='ceo',
            field=models.OneToOneField(blank=True, default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='business_ceo', to='user.customuser'),
            preserve_default=False,
        ),
    ]
