# Generated by Django 3.2.5 on 2021-12-03 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_business_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='invitations',
            field=models.ManyToManyField(blank=True, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
